on:
  push:
    branches:
      - main  # Запускать пайплайн при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать пайплайн при создании пул-реквеста в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Указываем версию Go

      - name: Run tests
        run: |
          cd go/test
          go test -v ./...