name: go ci-cd

on:
  push:
    branches:
      - main   # Запускать пайплайн при пуше в ветку main
      - v0.8

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Указываем версию Go
      
      - name: Run port check (+install JQ)
        run: |
          sudo apt-get install -y jq   # Установка зависимости для работы с JSON
          chmod +x tests/port_check.sh  # Даем права на выполнение скрипта
          ./tests/port_check.sh         # Запускаем скрипт проверки портов

      - name: Run tests
        run: |
          cd go/
          go test -v